/********************************************************\
| WARNING:                                               |
| Do not edit `src\main\resources\stats\metrics.js file. |
| It is autogenerated.                                   |
| Make changes in `src\main\jsx\metrics.js`.             |
\********************************************************/

var Nodes = (function(){

  var Nodes = React.createClass({
    parseItem: function(rawData) {
      var arr = rawData.split('::');
      return {
        name:  arr[0],
        node:  arr[1],
        param: arr[2],
        time:  arr[3],
        value: arr[4]
      }
    },
    add: function(oldData,newItem) {
      // copy old data
      var result = {};
      for (name of Object.keys(oldData)) {
        result[name] = {};
        for (node of Object.keys(oldData[name])) {
          result[name][node] = {};
          result[name][node]['time'] = oldData[name][node]['time'];
          result[name][node]['param'] = {};
          for (param of Object.keys(oldData[name][node]['param']))
            result[name][node]['param'][param] = oldData[name][node]['param'][param];
        }
      }
      // add new item
      result[newItem.name] = result[newItem.name] || {};
      result[newItem.name][newItem.node] = result[newItem.name][newItem.node] || {};
      result[newItem.name][newItem.node]['param'] = result[newItem.name][newItem.node]['param'] || {};
      result[newItem.name][newItem.node]['param'][newItem.param] = newItem.value;
      result[newItem.name][newItem.node]['time'] = newItem.time;
      return result;
    },
    getInitialState: function() {
      return {data:{},activeName:null,details:null}
    },
    componentDidMount: function() {
      this.props.handlers.metric = function(msg) {
        if (this.isMounted()) {
          var oldData = this.state.data;
          var newItem = this.parseItem(msg);
          var data = this.add(oldData,newItem);
          var activeName = this.state.activeName !== null ? this.state.activeName : newItem.name;
          this.setState({data:data,activeName:activeName})
        }
      }.bind(this);
    },
    handleChooseTab: function(tab) {
      this.setState({activeName:tab.props.name,details:null})
    },
    handleChooseRow: function(node) {
      this.setState({details:{name:this.state.activeName,node:node}})
    },
    render: function() {
      var data = this.state.data;
      var names = Object.keys(data);
      var el;
      if (names.length === 0)
        el = <div className="alert alert-info">Please wait...</div>
      else {
        var activeName = this.state.activeName;
        el =
          <div className="row">
            <div className="col-sm-6 col-md-5 col-lg-4">
              <Tabs names={names} active={activeName} onChoose={this.handleChooseTab} />
              <Table nameData={data[activeName]} onChooseRow={this.handleChooseRow} />
            </div>
            {(() => {
            var details = this.state.details;
            if (details !== null) return (
            <div className="col-sm-6 col-md-5 col-lg-8">
              <div className="row">
                <div className="col-xs-12">
                  <h3 style={{marginTop:0}}>{details.name}@{details.node}</h3>
                </div>
              </div>
              <div className="row">
                <div className="col-lg-6">
                  <h4>Metrics</h4>
                  <Metrics data={data[details.name][details.node]['param']} name={details.name} node={details.node} />
                </div>
              </div>
            </div>
            )})()}
          </div>
      }
      return <div className="col-xs-12">{el}</div>
    }
  });

  var Tabs = React.createClass({
    render: function() {
      var tabs = this.props.names.map(function(name,i) {
        var active = name === this.props.active;
        return <Tab name={name} active={active} onChoose={this.props.onChoose} key={i} />;
      }.bind(this));
      return <ul className="nav nav-pills">{tabs}</ul>;
    }
  });

  var Tab = React.createClass({
    handleChoose: function() {
      this.props.onChoose(this);
    },
    render: function() {
      var className = this.props.active ? 'active' : '';
      return (
        <li role="presentation" className={className}>
          <a href="#" onClick={this.handleChoose}>{this.props.name}</a>
        </li>
      );
    }
  });

  var Table = React.createClass({
    render: function() {
      var nameData = this.props.nameData;
      var rows = Object.keys(nameData).map(function(node,i) {
        return <Row node={node}
                    nodeData={nameData[node]}
                    onChoose={this.props.onChooseRow}
                    key={i} />
      }.bind(this));
      var minWidth = {width:'1px'}
      return (
        <div className="table-responsive" style={{marginTop:'10px'}}>
          <table className="table">
            <thead>
              <tr>
                <th>Node</th>
                <th style={minWidth}>Status</th>
              </tr>
            </thead>
            <tbody>{rows}</tbody>
          </table>
        </div>
      );
    }
  });

  var Row = React.createClass({
    componentDidMount: function() {
      this.timer = setInterval(this.tick, 1000);
    },
    componentWillUnmount: function() {
      clearInterval(this.timer);
    },
    tick: function() {
      this.forceUpdate();
    },
    handleChoose: function() {
      this.props.onChoose(this.props.node);
    },
    render: function() {
      var elapsed = Math.floor((new Date() - this.props.nodeData["time"]) / 1000);
      var active = elapsed < 5;
      return (
        <tr className={active ? "success" : "danger"} style={{cursor:'pointer'}} onClick={this.handleChoose}>
          <td>{this.props.node}</td>
          <td>
          {(() => {
            if (active) return <div style={{textAlign:'center'}}>OK</div>;
            else return <div><span style={{whiteSpace:'nowrap'}}>{secToTimeInterval(elapsed)}</span> ago</div>;
          })()}
          </td>
        </tr>
      );
    }
  });

  var Metrics = React.createClass({
    render: function() {
      var data = this.props.data;
            var cpu_val = Math.round(+(data['cpu.load']*100));
            var mem_val = Math.round(+(data['mem.used'] / data['mem.total'] * 100));
            var fs_val = Math.round(+(data['root./.used'] / data['root./.total'] * 100));

      return (
        <div>
          <div>
            <StatsGauge gauge_id={'gauge_'+this.props.name+'_'+this.props.node} cpu_val={cpu_val} mem_val={mem_val} fs_val={fs_val}   />
          </div>
          <ul className="list-group">
            <li className="list-group-item">
              <span className="badge">{secToTimeInterval(Number(data['sys.uptime']))}</span>
              Uptime
            </li>
            <li className="list-group-item">
              <span title="MB" className="badge">{bytesToMb(Number(data['mem.used']))}</span>
              Memory Used
            </li>
            <li className="list-group-item">
              <span title="MB" className="badge">{bytesToMb(Number(data['mem.free']))}</span>
              Memory Free
            </li>
            <li className="list-group-item">
              <span title="MB" className="badge">{bytesToMb(Number(data['mem.total']))}</span>
              Memory Total
            </li>
            <li className="list-group-item">
              <span title="GB" className="badge">{kbToGb(Number(data['root./.used']))}</span>
              FS Used
            </li>
            <li className="list-group-item">
              <span title="GB" className="badge">{kbToGb(Number(data['root./.free']))}</span>
              FS Free
            </li>
            <li className="list-group-item">
              <span title="GB" className="badge">{kbToGb(Number(data['root./.total']))}</span>
              FS Total
            </li>
          </ul>
        </div>
      );
    }
  });

  var StatsGauge = React.createClass({
    getInitialState: function() {
      var data = google.visualization.arrayToDataTable([
        ['Label', 'Value'],
        ['Memory', 0],
        ['CPU', 0],
        ['FS', 0]
      ]);

      var max = +(this.props.max)
      var options = {
        width: 400, height: 120,
        redFrom: 90, redTo: 100,
        yellowFrom:75, yellowTo: 90,
        minorTicks: 5
      };
      return {options:options,data:data,chart:null};
    },
    componentDidMount: function() {
      var chart = new google.visualization.Gauge(document.getElementById(this.props.gauge_id));
      this.setState({chart:chart});
      this.draw();
    },
    componentDidUpdate: function() {
      this.draw();
    },
    draw: function() {
      this.state.data.setValue(0, 1, this.props.mem_val);
      this.state.data.setValue(1, 1, this.props.cpu_val);
      this.state.data.setValue(2, 1, this.props.fs_val);
      if (this.state.chart !== null)
        this.state.chart.draw(this.state.data,this.state.options);
    },
    render: function() {
      return <div id={this.props.gauge_id}></div>;
    }
  });

  return Nodes;
})();